# Generated by Django 4.2.4 on 2023-09-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=64)),
                ("bid", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=64)),
                ("comment", models.CharField(max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("clothing", "Clothing"),
                            ("sportingGoods", "Sporting Goods"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.CharField(max_length=144)),
                ("imgUrl", models.CharField(max_length=64)),
                ("owner", models.CharField(max_length=64)),
                ("startingBid", models.DecimalField(decimal_places=2, max_digits=6)),
                ("title", models.CharField(max_length=64)),
            ],
        ),
    ]
