# Generated by Django 4.2.4 on 2023-10-06 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="listing",
            new_name="listing_id",
        ),
    ]
