# Generated by Django 4.2.4 on 2023-10-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_rename_listing_comment_listing_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
