# Generated by Django 4.2.4 on 2023-10-04 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_listing_imgurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchers",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="listing",
            name="imgUrl",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
