# Generated by Django 4.2.4 on 2023-10-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_listing_watchers_alter_listing_imgurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
