# Generated by Django 4.2.4 on 2023-10-19 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_rename_listing_id_bid_listing_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="listing",
            new_name="listing_id",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="listing",
            new_name="listing_id",
        ),
    ]
