# Generated by Django 4.2.4 on 2023-10-19 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_alter_bid_user_alter_comment_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="user",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="listing",
            name="owner",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="listing",
            name="watchers",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="listing",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="watching",
            field=models.ManyToManyField(
                blank=True, related_name="watching", to="auctions.listing"
            ),
        ),
    ]
