# Generated by Django 4.2.4 on 2023-10-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_alter_bid_user_alter_comment_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="watching",
            field=models.ManyToManyField(
                blank=True, related_name="watching", to="auctions.listing"
            ),
        ),
    ]
