# Generated by Django 4.2.4 on 2023-10-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0015_remove_listing_watchers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("auto", "Auto"),
                    ("clothing", "Clothing"),
                    ("electronics", "Electronics"),
                    ("home", "Home"),
                    ("jewelry", "Jewelry"),
                    ("sportingGoods", "Sporting Goods"),
                    ("toys", "Toys"),
                ],
                max_length=32,
            ),
        ),
    ]
