# Generated by Django 4.2.4 on 2023-10-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_alter_user_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
