# Generated by Django 4.2.4 on 2023-10-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_alter_post_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.CharField(max_length=280),
        ),
    ]
